CREATE database mydatabase; 
USE mydatabase;
SELECT * FROM mytable;

-- Q1. what is the total revenue generated by male vs. female customers?
SELECT gender, SUM(purchase_amount) AS revenue 
FROM mytable 
GROUP BY gender;

-- Q2. which customer used a discount but still spent more than the average puchese amount ?
SELECT customer_id, purchase_amount
FROM mytable 
WHERE discount_applied = 'yes' AND purchase_amount >= (SELECT AVG(purchase_amount) FROM mytable);

-- Q3. which are the top 5 products with the highest average review rating ?
SELECT item_purchased, ROUND(AVG(review_rating), 2) AS `average product rating`
FROM mytable
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;

-- Q4. compare  the average purchese amount between standerd and express shipping. 
SELECT shipping_type,
ROUND(AVG(purchase_amount), 2)
FROM mytable
WHERE shipping_type in ('Express','Standard')
GROUP BY shipping_type;

-- Q5. do subscribed customer spend more ? compare average spend and total revenue between subscribers and non subscribers 
SELECT subscription_status,
COUNT(customer_id) AS total_customers,
ROUND(AVG(purchase_amount),2) AS avg_spend,
ROUND(SUM(purchase_amount),2) AS total_revenue
FROM mytable
GROUP BY subscription_status
ORDER BY total_revenue, avg_spend desc;

-- Q6. which 5 products have the heist percentage of purcheses with discounts applied?
SELECT item_purchased,
ROUND(SUM(CASE WHEN discount_applied = 'yes' THEN 1 ELSE 0 END)/ COUNT(*) * 100, 2) AS discount_rate
FROM mytable
GROUP BY item_purchased
ORDER BY discount_rate desc
LIMIT 5;

-- Q7. segment customers into new returing, and loyal based on their total numbers of purcheses and show the count of each segment 
WITH customer_type AS (
SELECT customer_id, previous_purchases,
CASE 
	WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
FROM mytable
)
SELECT customer_segment, COUNT(*) AS 'Number of costomers'
FROM customer_type
GROUP BY customer_segment ;

-- Q8. what are the top 3 most purchased product within each category ?
WITH item_count AS(
SELECT category, item_purchased,
COUNT(customer_id) AS total_orders,
ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
FROM mytable
GROUP BY category, item_purchased
)
SELECT item_rank, category, item_purchased, total_orders
FROM item_count
WHERE item_rank <= 3;

-- Q9. are custommers who are repeat byers(more than 5 previous purchases)also likly to subscribe?
SELECT subscription_status,
COUNT(customer_id) AS repeat_buyers
FROM mytable
WHERE previous_purchases > 5
GROUP BY subscription_status;

-- Q10. what is the revenue contribution of each age group
SELECT age_group,
COUNT(purchase_amount) AS total_revenue
FROM mytable
GROUP BY age_group
ORDER BY total_revenue DESC;






